# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :categories/:title

# Site settings
title: Wilson Tayar
tagline: //@wilsontayar
description: Follow me <a href='https://twitter.com/wilsontayar'>@wilsontayar</a>

url: http://www.wilsontayar.com

author:
  name: Wilson Tayar
  url: https://twitter.com/wilsontayar
email: wilsontayar at hotmail dot com

# Custom vars
version:             1.0.0
